# importing

In [1]:
import pandas as pd

# Reading File

In [2]:
df = pd.read_excel(r"C:\Users\Admin\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

# Removing Duplicates

In [10]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/97,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Yes,N

# Removing column that is useless

In [4]:
df = df.drop(columns = 'Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Removing unnecessary string chars in "last name" col

In [5]:
df["Last_Name"] = df["Last_Name"].str.lstrip("...")
df["Last_Name"] = df["Last_Name"].str.lstrip("/")
df["Last_Name"] = df["Last_Name"].str.rstrip("_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

# Similar Formatting Phone Numbers

In [40]:
df["Phone_Number"] = df["Phone_Number"].str.replace('-','')
df["Phone_Number"] = df["Phone_Number"].str.replace('|','')
df["Phone_Number"] = df["Phone_Number"].str.replace('nan','')
df["Phone_Number"] = df["Phone_Number"].str.replace('/','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,12354323,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,87667834,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

Converting Data Types from numbers to strings

In [41]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x:str(x))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,12354323,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,87667834,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

Inserting '-' inbetween numbers in their preferred position using lambda function

In [42]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '' + x[3:6] + '' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,12354554,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,87667834,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,87667834,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,12354554,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,12354323,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,87667834,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,30476224,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,12354554,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,12364397,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,87667834,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

# splitting address column by no. , state, zip-code

In [47]:
df["Address"].str.split(',',expand = True)

                       0              1
0         123 Shire Lane          Shire
2     298 Drugs Driveway           None
4       123 Dragons Road           None
6      1209 South Street           None
7          98 Clue Drive           None
9       25th Main Street       New York
10        612 Shire Lane          Shire
11  2394 Hogwarts Avenue           None
12      2039 Main Street           None
13      343 City Parkway           None
14         214 HR Avenue           None
15  2395 Hogwarts Avenue           None
16      121 Paper Avenue   Pennsylvania
17       3498 Super Lane           None
19     910 Tatooine Road       Tatooine

# replacing 'yes' -> y and 'no' - n

In [21]:
df["Paying Customer"] = df["Paying Customer"].str.replace('Yes','Y')
df["Paying Customer"] = df["Paying Customer"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/97,93 West Main Street,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [23]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

# Replacing 'N/A' with  ' '  in all columns

In [29]:
df = df.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123/643/97,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,,,Y,,None,None
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

# Replacing all null values with a blank

In [30]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/97,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-23,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-24,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

# CASE STUDY:

The Call Center only wants the data of people having phone numbers and those who they CAN contact/call

drop based on index

In [32]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"] == 'Y': # here df.loc implies that filtering is done based on index
        df.drop(x, inplace = True)
        
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

we also do not want the people who didn't provide any phone numbers

In [33]:
for x in df.index:
    if df.loc[x,"Phone_Number"] == '': # here df.loc implies that filtering is done based on index
        df.drop(x, inplace = True)
        
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

# Resetting Index

In [34]:
df.reset_index(drop = True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_Address,state,zip-code
0,1001,Frodo,Baggins,123-545-54,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,7066950392,298 Drugs Driveway,N,,298 Drugs Driveway,,
2,1005,Jon,Snow,876|678|34,123 Dragons Road,Y,N,123 Dragons Road,,
3,1007,Jeff,Winger,nan,1209 South Street,N,N,1209 South Street,,
4,1008,Sherlock,Holmes,876|678|34,98 Clue Drive,N,N,98 Clue Drive,,
5,1010,Peter,Parker,123-545-54,"25th Main Street, New York",Y,N,25th Main Street,New York,
6,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
7,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
8,1013,Don,Draper,123-543-23,2039 Main Street,Y,N,2039 Main Street,,
9,1014,Leslie,Knope,876|678|34,343 City Parkway,Y,N,343 City Parkway,,
10,1015,Toby,Flenderson,304-762-24,214 HR Avenue,N,N,214 HR Avenue,,
11,1016,Ron,Weasley,123-545-54,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
12,1017,Michael,Scott,123/643/97,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
13,1018,Clark,Kent,7066950392,3498 Super Lane,Y,,3498 Super Lane,,
14,1020,Anakin,Skywalker,876|678|34,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

# Exporting As a CSV/Excel File

In [55]:
df.to_excel(r'C:\Users\Admin\Downloads\Customer_Call_List.xlsx', index =False)

In [57]:
df.to_csv(r'C:\Users\Admin\Downloads\Customer_Call_List.csv', index =False)